import "@ocean-network-express/magenta-react/index.css";
import type { Metadata } from "next";
import "./globals.css";
import { ApolloProviderComponent } from "./providers/apolloProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //
  return (
    <html lang="en">
      <body>
        <ApolloProviderComponent>{children}</ApolloProviderComponent>
      </body>
    </html>
  );
}
